# Site settings
title: Dawns 48th
email: ridinginaction@gmail.com
tel: 01793 847909
addr: Hangar C2, Wroughton Airfield, Swindon, SN4 0QT
url: https://dawn.geyemokay.uk
description: "A life worth living"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Dawn's 48th Birthday

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
gmaps_api_key: ENV['GMAPS_API_KEY']
